.ifndef SCR_SEQ_T26R0601_H_
.definelabel SCR_SEQ_T26R0601_H_, 0

.equ _EV_scr_seq_T26R0601_000, 0
.equ _EV_scr_seq_T26R0601_001, 1
.equ _EV_scr_seq_T26R0601_002, 2
.equ _EV_scr_seq_T26R0601_003, 3
.equ _EV_scr_seq_T26R0601_004, 4

.equ obj_T26R0601_sunglasses, 0
.equ obj_T26R0601_maid, 1
.equ obj_T26R0601_follower_mon_clefable, 2
.equ obj_T26R0601_follower_mon_sunflora, 3
.equ obj_T26R0601_gsbabyboy1, 4

.endif //SCR_SEQ_T26R0601_H_
