.ifndef SCR_SEQ_T08_H_
.definelabel SCR_SEQ_T08_H_, 0

.equ _EV_scr_seq_T08_000, 0
.equ _EV_scr_seq_T08_001, 1
.equ _EV_scr_seq_T08_002, 2
.equ _EV_scr_seq_T08_003, 3
.equ _EV_scr_seq_T08_004, 4
.equ _EV_scr_seq_T08_005, 5
.equ _EV_scr_seq_T08_006, 6
.equ _EV_scr_seq_T08_007, 7
.equ _EV_scr_seq_T08_008, 8
.equ _EV_scr_seq_T08_009, 9
.equ _EV_scr_seq_T08_010, 10
.equ _EV_scr_seq_T08_011, 11
.equ _EV_scr_seq_T08_012, 12
.equ _EV_scr_seq_T08_013, 13
.equ _EV_scr_seq_T08_014, 14
.equ _EV_scr_seq_T08_015, 15
.equ _EV_scr_seq_T08_016, 16
.equ _EV_scr_seq_T08_017, 17
.equ _EV_scr_seq_T08_018, 18
.equ _EV_scr_seq_T08_019, 19

.equ obj_T08_gsmiddleman1, 0
.equ obj_T08_gswoman1, 1
.equ obj_T08_gsboy2, 2
.equ obj_T08_tree, 3
.equ obj_T08_bonguri, 4
.equ obj_T08_gsmiddleman1_2, 5
.equ obj_T08_juggrer, 6
.equ obj_T08_follower_mon_shellder, 7
.equ obj_T08_follower_mon_shellder_2, 8
.equ obj_T08_follower_mon_shellder_3, 9
.equ obj_T08_follower_mon_shellder_4, 10
.equ obj_T08_follower_mon_shellder_5, 11
.equ obj_T08_follower_mon_shellder_6, 12
.equ obj_T08_follower_mon_shellder_7, 13
.equ obj_T08_follower_mon_cloyster, 14
.equ obj_T08_follower_mon_shellder_8, 15
.equ obj_T08_follower_mon_shellder_9, 16
.equ obj_T08_follower_mon_shellder_10, 17
.equ obj_T08_follower_mon_shellder_11, 18
.equ obj_T08_woman1, 19
.equ obj_T08_follower_mon_cloyster_2, 20
.equ obj_T08_follower_mon_shellder_12, 21
.equ obj_T08_follower_mon_shellder_13, 22
.equ obj_T08_follower_mon_shellder_14, 23
.equ obj_T08_gsgirl1, 24
.equ obj_T08_follower_mon_cloyster_3, 25
.equ obj_T08_follower_mon_cloyster_4, 26
.equ obj_T08_follower_mon_venomoth, 27
.equ obj_T08_follower_mon_static_chansey, 28
.equ obj_T08_gsleader13, 29
.equ obj_T08_pcwoman1, 30

.endif //SCR_SEQ_T08_H_
