.ifndef SCR_SEQ_T25SP0101_H_
.definelabel SCR_SEQ_T25SP0101_H_, 0

.equ _EV_scr_seq_T25SP0101_000, 0
.equ _EV_scr_seq_T25SP0101_001, 1
.equ _EV_scr_seq_T25SP0101_002, 2
.equ _EV_scr_seq_T25SP0101_003, 3
.equ _EV_scr_seq_T25SP0101_004, 4
.equ _EV_scr_seq_T25SP0101_005, 5
.equ _EV_scr_seq_T25SP0101_006, 6
.equ _EV_scr_seq_T25SP0101_007, 7
.equ _EV_scr_seq_T25SP0101_008, 8
.equ _EV_scr_seq_T25SP0101_009, 9
.equ _EV_scr_seq_T25SP0101_010, 10
.equ _EV_scr_seq_T25SP0101_011, 11

.equ obj_T25SP0101_suit, 0
.equ obj_T25SP0101_gsgentleman, 1
.equ obj_T25SP0101_gsgentleman_2, 2
.equ obj_T25SP0101_gswoman6, 3
.equ obj_T25SP0101_follower_mon_bellossom, 4
.equ obj_T25SP0101_follower_mon_wynaut, 5
.equ obj_T25SP0101_follower_mon_wobbuffet_f, 6
.equ obj_T25SP0101_follower_mon_spinda, 7
.equ obj_T25SP0101_follower_mon_ludicolo, 8

.endif //SCR_SEQ_T25SP0101_H_
