.ifndef SCR_SEQ_T09_H_
.definelabel SCR_SEQ_T09_H_, 0

.equ _EV_scr_seq_T09_000, 0
.equ _EV_scr_seq_T09_001, 1
.equ _EV_scr_seq_T09_002, 2
.equ _EV_scr_seq_T09_003, 3
.equ _EV_scr_seq_T09_004, 4
.equ _EV_scr_seq_T09_005, 5
.equ _EV_scr_seq_T09_006, 6
.equ _EV_scr_seq_T09_007, 7
.equ _EV_scr_seq_T09_008, 8
.equ _EV_scr_seq_T09_009, 9
.equ _EV_scr_seq_T09_010, 10

.equ obj_T09_gsleader16, 0
.equ obj_T09_gsleader15, 1
.equ obj_T09_monstarball, 2
.equ obj_T09_follower_mon_heatran, 3

.endif //SCR_SEQ_T09_H_
