.ifndef SCR_SEQ_T24R0701_H_
.definelabel SCR_SEQ_T24R0701_H_, 0

.equ _EV_scr_seq_T24R0701_000, 0
.equ _EV_scr_seq_T24R0701_001, 1
.equ _EV_scr_seq_T24R0701_002, 2
.equ _EV_scr_seq_T24R0701_003, 3
.equ _EV_scr_seq_T24R0701_004, 4

.equ obj_T24R0701_sunglasses, 0
.equ obj_T24R0701_sunglasses_2, 1
.equ obj_T24R0701_follower_mon_gligar, 2
.equ obj_T24R0701_follower_mon_sneasel, 3

.endif //SCR_SEQ_T24R0701_H_
