.ifndef SCR_SEQ_D42R0101_H_
.definelabel SCR_SEQ_D42R0101_H_, 0

.equ _EV_scr_seq_D42R0101_000, 0
.equ _EV_scr_seq_D42R0101_001, 1
.equ _EV_scr_seq_D42R0101_002, 2
.equ _EV_scr_seq_D42R0101_003, 3
.equ _EV_scr_seq_D42R0101_004, 4

.equ obj_D42R0101_sunglasses, 0
.equ obj_D42R0101_monstarball, 1
.equ obj_D42R0101_monstarball_2, 2
.equ obj_D42R0101_follower_mon_registeel, 3
.equ obj_D42R0101_monstarball_3, 4
.equ obj_D42R0101_diancie, 5
.equ obj_D42R0101_collector, 6

.endif //SCR_SEQ_D42R0101_H_
