.ifndef SCR_SEQ_D38R0104_H_
.definelabel SCR_SEQ_D38R0104_H_, 0

.equ _EV_scr_seq_D38R0104_000, 0
.equ _EV_scr_seq_D38R0104_001, 1
.equ _EV_scr_seq_D38R0104_002, 2
.equ _EV_scr_seq_D38R0104_003, 3

.equ obj_D38R0104_rock, 0
.equ obj_D38R0104_gsfighter, 1
.equ obj_D38R0104_monstarball, 2
.equ obj_D38R0104_monstarball_2, 3
.equ obj_D38R0104_monstarball_3, 4
.equ obj_D38R0104_monstarball_4, 5
.equ obj_D38R0104_monstarball_5, 6
.equ obj_D38R0104_follower_mon_regirock, 7
.equ obj_D38R0104_follower_mon_jirachi, 8

.endif //SCR_SEQ_D38R0104_H_
